In [1]:
import pandas as pd

In [2]:
tweets_df = pd.read_csv('data\\Cleaned_Tweets.csv',index_col = False)
reddit_df = pd.read_csv('data\\Cleaned_Reddit.csv',index_col = False)

In [16]:
tweets_df.head()

,User,Date Created,Number of Likes,Number of Retweets,Source of Tweet,Tweet,Language,URL,Cleaned Data,Tokenized Data,Tokenized Clean Data,Tokenized LowerCase Data,Tokenized Clean LowerCase Data
0,RivalTimes,2022-11-01 23:52:17+00:00,0,0,Jetpack.com,Why is it not enough that Ralph Lauren has wit...,en,https://twitter.com/RivalTimes/status/15875934...,Why not enough Ralph Lauren withdrawn sacks co...,"['Why', 'is', 'it', 'not', 'enough', 'that', '...","['Why', 'not', 'enough', 'Ralph', 'Lauren', 'w...","['why', 'is', 'it', 'not', 'enough', 'that', '...","['why', 'not', 'enough', 'ralph', 'lauren', 'w..."
1,adrisa24,2022-11-01 23:48:59+00:00,0,0,Poshmark,Check out this listing I just added to my Posh...,en,https://twitter.com/adrisa24/status/1587592568...,Check listing I added Poshmark closet LAUREN R...,"['Check', 'out', 'this', 'listing', 'I', 'just...","['Check', 'listing', 'I', 'added', 'Poshmark',...","['check', 'out', 'this', 'listing', 'i', 'just...","['check', 'listing', 'i', 'added', 'poshmark',..."
2,FortniteBoards,2022-11-01 23:42:09+00:00,0,0,FortniteBoards Social Auto Post,Fortnites Polo Ralph Lauren Crossover Brings ...,en,https://twitter.com/FortniteBoards/status/1587...,Fortnites Polo Ralph Lauren Crossover Brings R...,"['Fortnites', 'Polo', 'Ralph', 'Lauren', 'Cros...","['Fortnites', 'Polo', 'Ralph', 'Lauren', 'Cros...","['fortnites', 'polo', 'ralph', 'lauren', 'cros...","['fortnites', 'polo', 'ralph', 'lauren', 'cros..."
3,GeyiPoji,2022-11-01 23:41:08+00:00,0,0,Jetpack.com,The Fortnite Crossover Ralph Lauren Polo Bring...,en,https://twitter.com/GeyiPoji/status/1587590596...,The Fortnite Crossover Ralph Lauren Polo Bring...,"['The', 'Fortnite', 'Crossover', 'Ralph', 'Lau...","['The', 'Fortnite', 'Crossover', 'Ralph', 'Lau...","['the', 'fortnite', 'crossover', 'ralph', 'lau...","['the', 'fortnite', 'crossover', 'ralph', 'lau..."
4,modcontrollerz,2022-11-01 23:39:48+00:00,0,0,Jetpack.com,Fortnites Polo Ralph Lauren Crossover Brings R...,en,https://twitter.com/modcontrollerz/status/1587...,Fortnites Polo Ralph Lauren Crossover Brings R...,"['Fortnites', 'Polo', 'Ralph', 'Lauren', 'Cros...","['Fortnites', 'Polo', 'Ralph', 'Lauren', 'Cros...","['fortnites', 'polo', 'ralph', 'lauren', 'cros...","['fortnites', 'polo', 'ralph', 'lauren', 'cros..."

In [17]:
reddit_df.head()

,Date,Subreddit,Title,Post Text,Author,Upvotes,CommentsCount,URL,Data,Cleaned Data,Tokenized Data,Tokenized Clean Data,Tokenized LowerCase Data,Tokenized Clean LowerCase Data
0,2022-11-04 17:57:33,1688Reps,QC on the 225 yuan Balenciaga Authentic jersey...,NaN,Paintballmania124,1,0,https://www.reddit.com//r/1688Reps/comments/ym...,nan QC on the yuan Balenciaga Authentic jerse...,QC yuan Balenciaga Authentic jersey apparel ho...,"['nan', 'QC', 'on', 'the', 'yuan', 'Balenciaga...","['QC', 'yuan', 'Balenciaga', 'Authentic', 'jer...","['nan', 'qc', 'on', 'the', 'yuan', 'balenciaga...","['qc', 'yuan', 'balenciaga', 'authentic', 'jer..."
1,2022-11-04 17:20:55,FashionReps,Balenciaga Track Clear Sole CSJ [Good batch],[removed],MakeTheCut_fjp,1,0,https://www.reddit.com//r/FashionReps/comments...,removed Balenciaga Track Clear Sole CSJ Good b...,Balenciaga Track Clear Sole CSJ Good batch,"['removed', 'Balenciaga', 'Track', 'Clear', 'S...","['Balenciaga', 'Track', 'Clear', 'Sole', 'CSJ'...","['removed', 'balenciaga', 'track', 'clear', 's...","['balenciaga', 'track', 'clear', 'sole', 'csj'..."
2,2022-11-04 17:20:16,QualityReps,About BALENCIAGA CROSS BOOTS - WWTOP,NaN,Competitive-Guide651,1,0,https://www.reddit.com//r/QualityReps/comments...,nan About BALENCIAGA CROSS BOOTS WWTOP,About BALENCIAGA CROSS BOOTS WWTOP,"['nan', 'About', 'BALENCIAGA', 'CROSS', 'BOOTS...","['About', 'BALENCIAGA', 'CROSS', 'BOOTS', 'WWT...","['nan', 'about', 'balenciaga', 'cross', 'boots...","['about', 'balenciaga', 'cross', 'boots', 'wwt..."
3,2022-11-04 17:16:13,QualityReps,About BALENCIAGA CROSS boots - WWTOP,NaN,Competitive-Guide651,1,0,https://www.reddit.com//r/QualityReps/comments...,nan About BALENCIAGA CROSS boots WWTOP,About BALENCIAGA CROSS boots WWTOP,"['nan', 'About', 'BALENCIAGA', 'CROSS', 'boots...","['About', 'BALENCIAGA', 'CROSS', 'boots', 'WWT...","['nan', 'about', 'balenciaga', 'cross', 'boots...","['about', 'balenciaga', 'cross', 'boots', 'wwt..."
4,2022-11-04 17:06:50,CryptoStock,Balenciaga Announces Bitcoin Payments – The BT...,NaN,asmajda,1,0,https://www.reddit.com//r/CryptoStock/comments...,nan Balenciaga Announces Bitcoin Payments The...,Balenciaga Announces Bitcoin Payments The BTC ...,"['nan', 'Balenciaga', 'Announces', 'Bitcoin', ...","['Balenciaga', 'Announces', 'Bitcoin', 'Paymen...","['nan', 'balenciaga', 'announces', 'bitcoin', ...","['balenciaga', 'announces', 'bitcoin', 'paymen..."

In [3]:
#Shuffling dataframe to extract 

from sklearn.utils import shuffle
shuffled_tweets = shuffle(tweets_df)
manual_label_tweets_df = shuffled_tweets['Tweet'][:2150]
manual_label_tweets_df = manual_label_tweets_df.to_frame()
manual_label_tweets_df.to_excel('label_tweets_-1or0or1.xlsx')

shuffled_reddit = shuffle(reddit_df)
manual_label_reddit_df = shuffled_reddit[["Title", "Data"]][:2150]
manual_label_reddit_df = manual_label_reddit_df
manual_label_reddit_df.to_excel('label_reddit_-1or0or1.xlsx')

,Title,Cleaned Data
11414,I forgot to post this when the dior car was av...,I forgot post dior car available D
26163,[WTS] 2002 Rolex Yacht-Master Ref. 16628 | Tah...,WTS Rolex YachtMaster Ref Tahitian MOP
31991,Here’s my keyboard. Also here’s my Rolex.,Heres keyboard Also heres Rolex
11947,What is a men's best cologne that is popular t...,Mens colognes important part personal grooming...
1633,Balenciaga campaign with children and teddy be...,Balenciaga campaign children teddy bears bonda...
...,...,...
25369,[Rolex] switching to crystal for ref. 1500 ? [...,Hi I tried figuring year oyster perpetual date...
2768,QC Foam Runner and Balenciaga Runner,Can someone helo qc theese Thank QC Foam Runne...
31609,(QC) Rolex Datejust 41 126334 904L SS VSF 1:1 ...,QC Rolex Datejust L SS VSF best Edition black ...
2314,I went to a Balenciaga theme park.,Nobody small go rides I went Balenciaga theme ...
13587,WTC polo ralph lauren bear wallet?,WTC polo ralph lauren bear wallet

In [14]:
shuffled_tweets = shuffle(tweets_df)
shuffled_tweets['Cleaned Data'][:500]

3141    philly_nyork Sassamadoo echo_chamberz well gav...
7811    Rolex Oyster Watch Link x size mm Free Shippin...
9470    Apprenticeship backbone trades decades industr...
2349     Christian Dior Men silk Blend Dress tie Blue wit
2790    Megan good Mariah scientist Lakeyah Dess Dior ...
                              ...
4600    FlLLEFATALE lot iconic fashion houses like cha...
6493    BramptonGraham osbcucscso Sflecce Public educa...
656     RalphLauren thegentsjournal JohnBoyega Shiiitt...
9135    Not knocking beautiful I love castiron pots pa...
9287    Rolex AD White Cotton Vintage New Event Golf S...
Name: Cleaned Data, Length: 500, dtype: object